### ISSUE TITLE
Error: Returned error: Wrong chainId

### ISSUE THREAD

**Issue by adityajoshi12** [ConsenSys/web3js-eea#145]
I am getting ```Error: Returned error: Wrong chainId``` when deploying the private contract. I have successfully created the privacy group and facing this issue while deploying the contract. I am following the example provided in this repository.
This is what I am doing
```
const createPrivateContract = (privacyGroupId) => {
  const contractOptions = {
    data: `0x${bytecode}`,
    privateFrom: orion.member1.publicKey,
    privacyGroupId: privacyGroupId,
    privateKey: besu.member1.privateKey,
  };
  return web3.eea.sendRawTransaction(contractOptions);
};
```
Error logs 
```
(node:29736) UnhandledPromiseRejectionWarning: Error: Returned error: Wrong chainId
    at Object.ErrorResponse (/home/innominds/nodejs-learning/besu-test-network/node-implementation/node_modules/web3-core-helpers/lib/errors.js:28:19)
    at /home/innominds/nodejs-learning/besu-test-network/node-implementation/node_modules/web3-core-requestmanager/lib/index.js:288:36
    at XMLHttpRequest.request.onreadystatechange (/home/innominds/nodejs-learning/besu-test-network/node-implementation/node_modules/web3-providers-http/lib/index.js:98:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/innominds/nodejs-learning/besu-test-network/node-implementation/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/home/innominds/nodejs-learning/besu-test-network/node-implementation/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/home/innominds/nodejs-learning/besu-test-network/node-implementation/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/home/innominds/nodejs-learning/besu-test-network/node-implementation/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:29736) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:29736) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by MadelineMurray** [comment]
Thanks for taking the time to raise @adityajoshi12 - we'll look at this.

**Comment by lucassaldanha** [comment]
Hi @adityajoshi12, could you please share the full script that you are using to create the private contract? I'm interested to see if you have the correct chainId when initializing the EEAClient.

Take a look at [this example](https://github.com/ConsenSys/web3js-eea/blob/master/example/multiNodeExample/deployContract.js#L13), here we are setting the chainId value to 2018. This value will be used to all txs sent by the EEAClient. And it must match your network's chainId.

**Comment by adityajoshi12** [comment]
Hi Folks,
I have resolved the issue, this was due to changing the consensus from _ibft2_ to _clique_. But still, I would like to know that if my Besu network was running on some other chainId (1981) how I was able to create privacy groups.

**Comment by lucassaldanha** [comment]
> Hi Folks,
> 
> I have resolved the issue, this was due to changing the consensus from _ibft2_ to _clique_. But still, I would like to know that if my Besu network was running on some other chainId (1981) how I was able to create privacy groups.

Hi! What privacy mode are you running? If you aren't running onchain privacy, the privacy group isn't created through a transaction, that would explain why you managed to create the privacy group.

If you share the config file you have used to run Besu, we can take a look to see if there is Anthony wrong .

Cheers!

**Comment by macfarla** [comment]
Hi @adityajoshi12, without further information we are unable to investigate this issue. Let us know if you're still having issues, in the meantime we will close this.
